Cell 1 - Import Libraries

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

Cell 2 - Load Cleaned Datasets

In [7]:
products = pd.read_csv("../data/cleaned/products.csv")
inventory = pd.read_csv("../data/cleaned/inventory.csv")
sales_lines = pd.read_csv("../data/cleaned/sales_lines.csv")

Cell 3 - Dataset Overview

In [8]:
datasets = {
    "Products": products,
    "Inventory": inventory,
    "Sales Lines": sales_lines
}

summary = pd.DataFrame({
    "Dataset": datasets.keys(),
    "Rows": [df.shape[0] for df in datasets.values()],
    "Columns": [df.shape[1] for df in datasets.values()]
})

summary

       Dataset    Rows  Columns
0     Products      30       25
1    Inventory     180        8
2  Sales Lines  130402        9

Cell 4 - Product Summary

In [9]:
print("PRODUCT SUMMARY")
print("-"*50)

print("Total Products :", products["product_id"].nunique())
print("Total Categories :", products["category"].nunique())
print("Total Brands :", products["brand"].nunique())
print("Total Machine Types :", products["machine_type"].nunique())

PRODUCT SUMMARY
--------------------------------------------------
Total Products : 30
Total Categories : 15
Total Brands : 6
Total Machine Types : 6

Cell 5 - Merge Product & Inventory Data

In [10]:
inventory_product = inventory.merge(
    products,
    on="product_id",
    how="left"
)

inventory_product.head()

,product_id,branch_id,opening_stock,reorder_level_x,safety_stock_x,max_stock,current_stock,warehouse_bin,product_name,category,machine_type,brand,model_compatibility,unit_cost,unit_price,margin_percentage,gst_rate,weight_kg,dimensions_cm,material_type,warranty_months,reorder_level_y,safety_stock_y,max_stock_level,lead_time_days,criticality_level,usage_frequency,uom,last_purchase_price,last_purchase_date,last_purchase_date_year,last_purchase_date_month
0,P001,Del001,196,59,46,340,115928,C15,Hydraulic Pump Hp-300,Hydraulic,Excavator,Cat,Cat 320D,18950,24500,29.2,28,38.5,40X25X25,Steel,12,15,10,40,21,High,Medium,Piece,18500,2019-03-15,2019,3
1,P001,Pun001,198,70,43,349,109389,D16,Hydraulic Pump Hp-300,Hydraulic,Excavator,Cat,Cat 320D,18950,24500,29.2,28,38.5,40X25X25,Steel,12,15,10,40,21,High,Medium,Piece,18500,2019-03-15,2019,3
2,P001,Chn001,187,62,44,311,99373,A11,Hydraulic Pump Hp-300,Hydraulic,Excavator,Cat,Cat 320D,18950,24500,29.2,28,38.5,40X25X25,Steel,12,15,10,40,21,High,Medium,Piece,18500,2019-03-15,2019,3
3,P001,Hyd001,226,71,65,417,108772,A10,Hydraulic Pump Hp-300,Hydraulic,Excavator,Cat,Cat 320D,18950,24500,29.2,28,38.5,40X25X25,Steel,12,15,10,40,21,High,Medium,Piece,18500,2019-03-15,2019,3
4,P001,Kol001,263,94,58,475,103808,F03,Hydraulic Pump Hp-300,Hydraulic,Excavator,Cat,Cat 320D,18950,24500,29.2,28,38.5,40X25X25,Steel,12,15,10,40,21,High,Medium,Piece,18500,2019-03-15,2019,3